const CONSTANTS = {
  MIN_SPAWN_DISTANCE: 100,
  OBSTACLE_DISTANCE: 220,
  ONE_OVER_SQRT_TWO: 1.0/Math.sqrt(2),
  SCREEN_HEIGHT: 600,
  SCREEN_WIDTH: 800,
  STOMACH_CONTENTS_MAX: 100,
  STOMACH_CONTENTS_STARTING: 20,
  STARTING_FOOD_AMOUNT: 3,
  STARTING_VILLAGER_AMOUNT: 2,
  VILLAGER_SPAWN_COUNT_UPON_DEATH: 2,
  WORLD_WIDTH: 3000,
  WORLD_HEIGHT: 3000
};

export { CONSTANTS };